; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:quatre_mb_huge]
board = esp32dev
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_ldf_mode = chain
framework = arduino
build_flags =
	-std=gnu++17
	-DARDUINOJSON_ENABLE_COMMENTS=1
	-DFREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
	-DCORE_DEBUG_LEVEL=1
	-frtti
	-Wall
	-Wextra
	-DMODBUSRTU_TIMEOUT=100
build_unflags =
	-fno-rtti
	-std=gnu++11
	-std=c++11
board_build.partitions = partitions_4MB_no_ota.csv
board_build.flash_size = 4MB
board_build.filesystem = littlefs
board_build.filesystem_size = 0x140000;
monitor_filters = esp32_exception_decoder, direct, log2file
build_type = debug
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	emelianov/modbus-esp8266@^4.1.0
	robtillaart/PCF8574@^0.4.1
	esp32async/AsyncTCP@3.5.0
	esp32async/ESPAsyncWebServer@3.12.0
	ArduinoJson@^7.3.0
	gin66/FastAccelStepper@^0.33.13
lib_ignore =
	AsyncTCP_RP2040W
	ESPAsyncTCP
	RPAsyncTCP

[env:esp32dev]
platform = espressif32
board = esp32dev
lib_ldf_mode = chain
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=gnu++17
	-DCONFIG_SPIRAM=1
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINOJSON_ENABLE_COMMENTS=1
	-DFREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
	-DCORE_DEBUG_LEVEL=1
	-frtti
	-Wall
	-Wextra
	-DMODBUSRTU_TIMEOUT=100
build_unflags = 
	-fno-rtti
	-std=gnu++11
	-std=c++11
board_build.partitions = partitions_16MB.csv
board_build.flash_size = 16MB
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder, direct, log2file
build_type = debug
upload_speed = 921600
lib_deps = 
	emelianov/modbus-esp8266@^4.1.0
	robtillaart/PCF8574@^0.4.1
	esp32async/AsyncTCP @ 3.3.8
	esp32async/ESPAsyncWebServer @ ^3.7.4
	ArduinoJson@^7.4.0
	gin66/FastAccelStepper@^0.33.13
lib_ignore =
	AsyncTCP_RP2040W
	ESPAsyncTCP
	RPAsyncTCP

[env:test_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_filters = 
	esp32_exception_decoder
	direct
	log2file
monitor_speed = 115200
test_framework = unity
lib_deps = 
	throwtheswitch/Unity @ ^2.6.0
	emelianov/modbus-esp8266@^4.1.0
	robtillaart/PCF8574@^0.4.1
	esp32async/AsyncTCP @ 3.3.8
	esp32async/ESPAsyncWebServer @ ^3.7.4
	ArduinoJson@^7.4.0
	gin66/FastAccelStepper@^0.33.13
lib_ignore =
	AsyncTCP_RP2040W
	ESPAsyncTCP
	RPAsyncTCP
	WebServer
build_flags = 
	-std=gnu++17
	-D UNIT_TEST_MODE
	-D UNIT_TEST
	-D ARDUINOJSON_ENABLE_COMMENTS=1
	-D CORE_DEBUG_LEVEL=0
	-frtti
	-D CONFIG_LITTLEFS_FOR_IDF_3_2
	-I test
	-I ${PROJECT_DIR}/test
	-D DEBUG_STATE_HISTORY
	-Wall
	-Wextra
	-fexec-charset=UTF-8
	-finput-charset=UTF-8
	-Wno-unused-parameter
	-fdiagnostics-show-option
	-DMODBUSRTU_TIMEOUT=100
build_src_filter = 
	+<BorneUniverselle/borneUniverselle.cpp>
	+<BorneUniverselle/*.cpp>
	+<BusinessLogic/*.cpp>
	+<MemoryMonitor/*.cpp>
	+<Node/*.cpp>
	+<PLC_Tools/*.cpp>
	+<PLC_Persistence/*.cpp>
	-<main.cpp>
build_unflags = 
	-fno-rtti
	-std=gnu++11
	-std=c++11
board_build.partitions = partitions_16MB_no_ota.csv
board_build.flash_size = 16MB
debug_build_flags = -O0 -g3 -ggdb3
test_build_src = no
test_speed = 115200
test_filter = test_*

[env:test_native]
platform = native
test_framework = unity
test_build_src = yes
build_flags = 
	-std=c++17
	-D UNIT_TEST
	-D NATIVE_TEST
build_unflags = 
	-std=c++11
	-DMODBUSRTU_TIMEOUT=100
lib_deps = 
	throwtheswitch/Unity @ ^2.5.2
	gin66/FastAccelStepper@^0.33.13